version: '3.8'
services:
  node:
    build: .
    image: node-image
    # container_name: node-app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - mongo
      - elasticsearch
      - redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  mongo:
    image: mongo
    volumes:
      - mongo-store:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
  redis:
    image: redis
    # volumes:
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    
volumes:
  mongo-store: